source 'http://rubygems.org'

gem 'rails', '3.0.0'
gem 'sqlite3'

group :test do
  gem 'rspec', '>= 2.0.0.beta.20'
  gem 'rspec-rails', '>= 2.0.0.beta.20'
  gem 'webrat'
  gem 'autotest'
  gem 'autotest-growl'
  gem 'autotest-fsevent'
  gem 'database_cleaner'
  gem 'spork'
  gem 'launchy'
end